---
server:
  address: 0.0.0.0:@autheliaPort@
  buffers:
    read: 16384
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'

log:
  level: warn

theme: auto


totp:
  issuer: authelia.@domainName@
  period: 30
  skew: 1

authentication_backend:
  password_reset:
    disable: true
  file:
    path: @usersFilePath@
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    - domain: "n8n.@domainName@"
      resources:
        - '^/form/.*'
      methods:
        - GET
        - POST
      policy: bypass
    - domain: "n8n.@domainName@"
      subject:
        - "user:nunu"
      policy: one_factor
    - domain: "*.@domainName@"
      subject:
        - "user:sweenu"
      policy: two_factor

session:
  expiration: 1h
  inactivity: 5m
  remember_me: 3M
  cookies:
    - domain: '@domainName@'
      authelia_url: 'https://authelia.@domainName@'
      default_redirection_url: 'https://@domainName@/'

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 10m

storage:
  local:
    path: @autheliaDataDir@/db.sqlite3

notifier:
  smtp:
    username: '@smtpUsername@'
    address: 'submissions://@smtpHost@:@smtpPort@'
    sender: 'Authelia <@email@>'
    identifier: '@domainName@'

password_policy:
  standard:
    enabled: true
    min_length: 8
    max_length: 0

ntp:
  address: "@ntpAddress@"
