---
server:
  host: 0.0.0.0
  port: @autheliaPort@

log:
  level: warn

theme: auto

default_redirection_url: https://searx.@domainName@/

totp:
  issuer: authelia.@domainName@
  period: 30
  skew: 1

authentication_backend:
  password_reset:
    disable: true
  file:
    path: @usersFilePath@
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    - domain: "searx.@domainName@"
      resources:
        - '^/opensearch\.xml(\?.*)?$'
      methods: [ GET ]
      policy: bypass
    - domain: "*.@domainName@"
      subject:
        - "user:sweenu"
      policy: two_factor

session:
  name: authelia_session
  domain: @domainName@
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 3M

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 10m

storage:
  local:
    path: @autheliaDataDir@/db.sqlite3

notifier:
  smtp:
    username: @smtpUsername@
    host: @smtpHost@
    port: @smtpPort@
    sender: Authelia <@email@>

password_policy:
  standard:
    enabled: true
    min_length: 8
    max_length: 0

ntp:
  address: "@ntpAddress@"
